# Apache reverse proxy config for Beacon v2 AF - ISCIII
<VirtualHost *:8080>
    ServerName beaconaf-isciiiciber.isciiides.es
    ServerAlias apibeacon-isciiiciber.isciiides.es
    
    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto "http"
    RequestHeader set X-Forwarded-Port "8443"
    SSLProxyEngine On
    SSLProxyVerify none
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerName off
    ProxyPass        /api https://beaconprod:5050/api
    ProxyPassReverse /api https://beaconprod:5050/api
    ProxyPass        / http://template-ui:3000/
    ProxyPassReverse / http://template-ui:3000/
    ErrorLog  /var/log/httpd/beacon-af.error.log
    CustomLog /var/log/httpd/beacon-af.access.log combined
</VirtualHost>
