# Apache reverse proxy config for Beacon v2 AF - ISCIII

ServerName beaconaf-isciiiciber.isciiides.es
# Beacon UI
<VirtualHost *:8080>
    ServerName beaconaf-isciiiciber.isciiides.es
    
    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto "http"
    RequestHeader set X-Forwarded-Port "8443"
    SSLProxyEngine On
    SSLProxyVerify none
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerName off
    ProxyPass        /api https://beaconprod:5050/api
    ProxyPassReverse /api https://beaconprod:5050/api
    ProxyPass        /admin-ui/ http://admin-ui:3001/
    ProxyPassReverse /admin-ui/ http://admin-ui:3001/
    ProxyPass        /static/adminui/ http://admin-ui:3001/static/adminui/
    ProxyPassReverse /static/adminui/ http://admin-ui:3001/static/adminui/
    ProxyPass        /static/admin/ http://admin-ui:3001/static/admin/
    ProxyPassReverse /static/admin/ http://admin-ui:3001/static/admin/
    ProxyPass        /auth/ http://idp:8082/auth/
    ProxyPassReverse /auth/ http://idp:8082/auth/
    ProxyPass        /mongo-express/ http://mongo-express:8081/mongo-express/
    ProxyPassReverse /mongo-express/ http://mongo-express:8081/mongo-express/
    ProxyPass        / http://template-ui:3000/
    ProxyPassReverse / http://template-ui:3000/
    ErrorLog  /var/log/httpd/beacon-af.error.log
    CustomLog /var/log/httpd/beacon-af.access.log combined
</VirtualHost>

# API Beacon
<VirtualHost *:8080>
    ServerName apibeacon-isciiiciber.isciiides.es

    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto "http"
    RequestHeader set X-Forwarded-Port "8443"

    SSLProxyEngine On
    SSLProxyVerify none
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerName off

    ProxyPass        /api https://beaconprod:5050/api
    ProxyPassReverse /api https://beaconprod:5050/api
</VirtualHost>
