systemLog:
  destination: file
  path: /var/log/mongodb/mongod.log
  logAppend: true
  logRotate: reopen
  verbosity: 0
  component:
   network:
    verbosity: -1

storage:
  wiredTiger:
   engineConfig:
    cacheSizeGB: 1

net:
  port: 27017
  bindIp: 0.0.0.0
#  tls:
#    mode: requireTLS
#    certificateKeyFile: /etc/mongo/certs/server.pem
#    CAFile: /etc/mongo/certs/ca.crt

security:
  authorization: enabled

processManagement:
  fork: false
